export default {
  "18~3": {
    "availablePhones": [
      'Existing Phone',
      'RingCentral for Desktop',
      'Polycom VVX 501 Color Touchscreen Phone with 1 Expansion Module',
      'Polycom IP 5000 Conference Phone',
      'Polycom IP 6000 Conference Phone',
      'Polycom VVX 501 Color Touchscreen Phone',
      'Cisco 7841 Gigabit Business Phone',
      'Cisco 8861 Gigabit Color Business Phone',
      'Polycom Trio 8500 Conference Phone',
      'Polycom Trio 8800 Conference Phone',
      'Yealink T42S Gigabit Business Phone',
      'Yealink T46S Gigabit Color Business Phone',
      'Yealink T46S Gigabit Color Business Phone with 2 Expansion Modules',
      'Yealink T46S Gigabit Color Business Phone with 1 Expansion Module',
      'Polycom VVX 150 Business IP Phone',
      'Polycom VVX 250 Business IP Phone',
      'Polycom VVX 350 Business IP Phone',
      'Polycom VVX 450 Business IP Phone',
      'Polycom VVX 450 Business IP Phone with 1 Expansion Module',
      'Yealink T48S Gigabit Color Touchscreen Business Phone with 2 Expansion Modules',
      'Yealink T48S Gigabit Color Touchscreen Business Phone with 1 Expansion Module',
      'Yealink T48S Gigabit Color Touchscreen Business Phone',
      'Yealink W60P Cordless Phone with 4 Handsets',
      'Yealink W60P Cordless Phone with 3 Handsets',
      'Yealink W60P Cordless Phone with 2 Handsets',
      'Yealink W60P Cordless Phone with 1 Handset',
      'Polycom OBi302 ATA',
      'Cisco CP8851 Gigabit Color Business Phone with 2 Expansion Modules',
      'Cisco CP8851 Gigabit Color Business Phone',
      'Cisco CP8851 Gigabit Color Business Phone with 1 Expansion Module',
      'Unify OpenScape Desk Phone CP700 with 2 Expansion Modules',
      'Unify OpenScape Desk Phone CP400 with 1 Expansion Module',
      'Unify OpenScape Desk Phone CP700 with 1 Expansion Module',
      'Unify OpenScape Desk Phone CP600 with 1 Expansion Module',
      'Unify OpenScape Desk Phone CP600 with 2 Expansion Modules',
      'Unify OpenScape Desk Phone CP700',
      'Cisco CP6821 Business IP Phone',
      'Unify OpenScape Desk Phone CP205',
      'Unify OpenScape Desk Phone CP400',
      'Unify OpenScape Desk Phone CP600',
      'Unify OpenScape Desk Phone CP100',
      'Unify OpenScape Desk Phone CP200',
      'Alcatel-Lucent 8008G Cloud Edition DeskPhone',
      'Yealink T57W Prime Business Phone',
      'Yealink T57W Prime Business Phone with 1 Expansion Module EXP50',
      'Yealink T57W Prime Business Phone with 2 Expansion Modules EXP50',
      'Alcatel-Lucent 8008 Cloud Edition DeskPhone',
      'Alcatel-Lucent 8018 Cloud Edition DeskPhone',
      'Alcatel-Lucent 8058s Cloud Edition Premium DeskPhone',
      'Alcatel-Lucent 8068s Cloud Edition Premium DeskPhone',
      'Polycom Trio 8300 Conference Phone',
      'Yealink T33G Gigabit Business Phone',
      'Yealink CP930W-Base Wireless DECT Conference phone',
      'Yealink W69P Cordless Phone with 1 Handset',
      'Poly CCX 400 Business Media Phone',
      'Poly CCX 500 Business Media Phone',
      'Poly CCX 600 Business Media Phone',
      'Poly CCX 700 Business Media Phone',
      'Yealink T53W Prime Business Phone',
      'Yealink T54W Prime Business Phone',
      'Yealink T43U Ultra-elegant Gigabit IP Phone',
      'Yealink T46U Ultra-elegant Gigabit IP Phone',
      'Yealink T48U Ultra-elegant Gigabit IP Phone',
      'Polycom IP 5000 Conference Phone - Rental',
      'Polycom IP 6000 Conference Phone - Rental',
      'Polycom VVX 501 Color Touchscreen Phone with 1 Expansion Module - Rental',
      'Polycom VVX 501 Color Touchscreen Phone - Rental',
      'Polycom IP 650 HD Executive IP phone with 3 Expansion Modules - Rental',
      'Polycom IP 650 HD Executive IP phone with 2 Expansion Modules - Rental',
      'Polycom IP 650 HD Executive IP phone with 1 Expansion Module - Rental',
      'Polycom IP 650 HD Executive IP phone - Rental',
      'Cisco 7841 Gigabit Business Phone - Rental',
      'Cisco 8861 Gigabit Color Business Phone - Rental',
      'Polycom Trio 8500 Conference Phone - Rental',
      'Polycom Trio 8800 Conference Phone - Rental',
      'Yealink T42S Gigabit Business Phone - Rental',
      'Yealink T46S Gigabit Color Business Phone - Rental',
      'Yealink T46S Gigabit Color Business Phone with 1 Expansion Module - Rental',
      'Yealink T46S Gigabit Color Business Phone with 2 Expansion Modules - Rental',
      'Polycom VVX 150 Business IP Phone - Rental',
      'Polycom VVX 250 Business IP Phone - Rental',
      'Polycom VVX 350 Business IP Phone - Rental',
      'Polycom VVX 450 Business IP Phone - Rental',
      'Polycom VVX 450 Business IP Phone with 1 Expansion Module - Rental',
      'Yealink T48S Gigabit Color Touchscreen Business Phone - Rental',
      'Yealink T48S Gigabit Color Touchscreen Business Phone with 1 Expansion Module - Rental',
      'Yealink T48S Gigabit Color Touchscreen Business Phone with 2 Expansion Modules - Rental',
      'Yealink W60P Cordless Phone with 1 Handset - Rental',
      'Yealink W60P Cordless Phone with 2 Handsets - Rental',
      'Yealink W60P Cordless Phone with 3 Handsets - Rental',
      'Yealink W60P Cordless Phone with 4 Handsets - Rental',
      'Polycom OBi302 ATA - Rental',
      'Cisco CP8851 Gigabit Color Business Phone - Rental',
      'Cisco CP8851 Gigabit Color Business Phone with 1 Expansion Module - Rental',
      'Cisco CP8851 Gigabit Color Business Phone with 2 Expansion Modules - Rental',
      'Unify OpenScape Desk Phone CP600 with 1 Expansion Module - Rental',
      'Unify OpenScape Desk Phone CP600 with 2 Expansion Modules - Rental',
      'Unify OpenScape Desk Phone CP400 with 1 Expansion Module - Rental',
      'Unify OpenScape Desk Phone CP700 with 1 Expansion Module - Rental',
      'Unify OpenScape Desk Phone CP700 with 2 Expansion Modules - Rental',
      'Cisco CP6821 Business IP Phone - Rental',
      'Unify OpenScape Desk Phone CP700 - Rental',
      'Unify OpenScape Desk Phone CP205 - Rental',
      'Unify OpenScape Desk Phone CP400 - Rental',
      'Unify OpenScape Desk Phone CP600 - Rental',
      'Unify OpenScape Desk Phone CP100 - Rental',
      'Unify OpenScape Desk Phone CP200 - Rental',
      'Yealink T57W Prime Business Phone - Rental',
      'Yealink T57W Prime Business Phone with 1 Expansion Module EXP50 - Rental',
      'Yealink T57W Prime Business Phone with 2 Expansion Modules EXP50 - Rental',
      'Polycom Trio 8300 Conference Phone - Rental',
      'Yealink T33G Gigabit Business Phone - Rental',
      'Yealink CP930W-Base Wireless DECT Conference phone - Rental',
      'Yealink W69P Cordless Phone with 1 Handset - Rental',
      'Poly CCX 400 Business Media Phone - Rental',
      'Poly CCX 500 Business Media Phone - Rental',
      'Poly CCX 600 Business Media Phone - Rental',
      'Poly CCX 700 Business Media Phone - Rental',
      'Yealink T53W Prime Business Phone - Rental',
      'Yealink T54W Prime Business Phone - Rental',
      'Yealink T43U Ultra-elegant Gigabit IP Phone - Rental',
      'Yealink T46U Ultra-elegant Gigabit IP Phone - Rental',
      'Yealink T48U Ultra-elegant Gigabit IP Phone - Rental',
      'Cisco SPA-122 ATA - Refurbished',
      'Cisco SPA-303 Desk Phone - Refurbished',
      'Cisco SPA-508G Desk Phone - Refurbished',
      'Cisco SPA-514G Desk Phone - Refurbished',
      'Cisco SPA-525G2 Desk Phone - Refurbished',
      'Polycom IP 5000 Conference Phone - Refurbished',
      'Polycom IP 6000 Conference Phone - Refurbished',
      'Polycom VVX 101 Basic IP Phone - Refurbished',
      'Polycom VVX 201 IP Phone - Refurbished',
      'Polycom VVX 310 Gigabit Ethernet Phone - Refurbished',
      'Polycom VVX 311 Gigabit Ethernet Phone - Refurbished',
      'Polycom VVX 410 Color Gigabit Ethernet Phone - Refurbished',
      'Polycom VVX 411 Color Gigabit Ethernet Phone - Refurbished',
      'Polycom VVX 500 Color Touchscreen Phone - Refurbished',
      'Polycom VVX 501 Color Touchscreen Phone - Refurbished',
      'Polycom VVX 601 Large Color Touchscreen Phone - Refurbished',
      'Cisco 7841 Gigabit Business Phone - Refurbished',
      'Cisco 8861 Gigabit Color Business Phone - Refurbished',
      'Polycom Trio 8500 Conference Phone - Refurbished',
      'Polycom Trio 8800 Conference Phone - Refurbished',
      'Yealink T42S Gigabit Business Phone - Refurbished',
      'Yealink T46S Gigabit Color Business Phone - Refurbished',
      'Polycom VVX 150 Business IP Phone - Refurbished',
      'Polycom VVX 250 Business IP Phone - Refurbished',
      'Polycom VVX 350 Business IP Phone - Refurbished',
      'Polycom VVX 450 Business IP Phone - Refurbished',
      'Yealink T48S Gigabit Color Touchscreen Business Phone - Refurbished',
      'Polycom OBi302 ATA - Refurbished',
      'Cisco CP8851 Gigabit Color Business Phone - Refurbished',
      'Unify OpenScape Desk Phone CP700 - Refurbished',
      'Cisco CP6821 Business IP Phone - Refurbished',
      'Unify OpenScape Desk Phone CP400 - Refurbished',
      'Unify OpenScape Desk Phone CP205 - Refurbished',
      'Unify OpenScape Desk Phone CP100 - Refurbished',
      'Unify OpenScape Desk Phone CP600 - Refurbished',
      'Unify OpenScape Desk Phone CP200 - Refurbished',
      'Yealink T57W Prime Business Phone - Refurbished',
      'Polycom Trio 8300 Conference Phone - Refurbished',
      'Yealink T33G Gigabit Business Phone - Refurbished',
      'Yealink CP930W-Base Wireless DECT Conference phone - Refurbished',
      'Yealink W69P Cordless Phone with 1 Handset - Refurbished',
      'Poly CCX 400 Business Media Phone - Refurbished',
      'Poly CCX 500 Business Media Phone - Refurbished',
      'Poly CCX 600 Business Media Phone - Refurbished',
      'Poly CCX 700 Business Media Phone - Refurbished',
      'Yealink T53W Prime Business Phone - Refurbished',
      'Yealink T54W Prime Business Phone - Refurbished',
      'Yealink T43U Ultra-elegant Gigabit IP Phone - Refurbished',
      'Yealink T46U Ultra-elegant Gigabit IP Phone - Refurbished',
      'Yealink T48U Ultra-elegant Gigabit IP Phone - Refurbished',
      'Poly Headset - Blackwire 3220 USB-A',
      'Poly Headset - Blackwire 3320 USB-A'
    ]
  },
  "20~1": {
    "availablePhones": [
      'Existing Phone',
      'RingCentral for Desktop',
      'Cisco SPA-122 ATA - Refurbished',
      'Cisco SPA-303 Desk Phone - Refurbished',
      'Cisco SPA-508G Desk Phone - Refurbished',
      'Cisco SPA-514G Desk Phone - Refurbished',
      'Cisco SPA-525G2 Desk Phone - Refurbished',
      'Polycom IP 5000 Conference Phone - Refurbished',
      'Polycom IP 6000 Conference Phone - Refurbished',
      'Polycom VVX 101 Basic IP Phone - Refurbished',
      'Polycom VVX 201 IP Phone - Refurbished',
      'Polycom VVX 310 Gigabit Ethernet Phone - Refurbished',
      'Polycom VVX 311 Gigabit Ethernet Phone - Refurbished',
      'Polycom VVX 410 Color Gigabit Ethernet Phone - Refurbished',
      'Polycom VVX 411 Color Gigabit Ethernet Phone - Refurbished',
      'Polycom VVX 500 Color Touchscreen Phone - Refurbished',
      'Polycom VVX 501 Color Touchscreen Phone - Refurbished',
      'Polycom VVX 601 Large Color Touchscreen Phone - Refurbished',
      'Cisco 7841 Gigabit Business Phone - Refurbished',
      'Cisco 8861 Gigabit Color Business Phone - Refurbished',
      'Polycom Trio 8500 Conference Phone - Refurbished',
      'Polycom Trio 8800 Conference Phone - Refurbished',
      'Yealink T42S Gigabit Business Phone - Refurbished',
      'Yealink T46S Gigabit Color Business Phone - Refurbished',
      'Polycom VVX 150 Business IP Phone - Refurbished',
      'Polycom VVX 250 Business IP Phone - Refurbished',
      'Polycom VVX 350 Business IP Phone - Refurbished',
      'Polycom VVX 450 Business IP Phone - Refurbished',
      'Yealink T48S Gigabit Color Touchscreen Business Phone - Refurbished',
      'Polycom OBi302 ATA - Refurbished',
      'Cisco CP8851 Gigabit Color Business Phone - Refurbished',
      'Unify OpenScape Desk Phone CP400 - Refurbished',
      'Unify OpenScape Desk Phone CP205 - Refurbished',
      'Unify OpenScape Desk Phone CP100 - Refurbished',
      'Unify OpenScape Desk Phone CP600 - Refurbished',
      'Unify OpenScape Desk Phone CP700 - Refurbished',
      'Cisco CP6821 Business IP Phone - Refurbished',
      'Unify OpenScape Desk Phone CP200 - Refurbished',
      'Yealink T57W Prime Business Phone - Refurbished',
      'Polycom Trio 8300 Conference Phone - Refurbished',
      'Yealink T33G Gigabit Business Phone - Refurbished',
      'Yealink CP930W-Base Wireless DECT Conference phone - Refurbished',
      'Yealink W69P Cordless Phone with 1 Handset - Refurbished',
      'Poly CCX 400 Business Media Phone - Refurbished',
      'Poly CCX 500 Business Media Phone - Refurbished',
      'Poly CCX 600 Business Media Phone - Refurbished',
      'Poly CCX 700 Business Media Phone - Refurbished',
      'Yealink T53W Prime Business Phone - Refurbished',
      'Yealink T54W Prime Business Phone - Refurbished',
      'Yealink T43U Ultra-elegant Gigabit IP Phone - Refurbished',
      'Yealink T46U Ultra-elegant Gigabit IP Phone - Refurbished',
      'Yealink T48U Ultra-elegant Gigabit IP Phone - Refurbished',
      'Polycom VVX 501 Color Touchscreen Phone with 1 Expansion Module',
      'Polycom IP 5000 Conference Phone',
      'Polycom IP 6000 Conference Phone',
      'Polycom VVX 501 Color Touchscreen Phone',
      'Cisco 7841 Gigabit Business Phone',
      'Cisco 8861 Gigabit Color Business Phone',
      'Polycom Trio 8500 Conference Phone',
      'Polycom Trio 8800 Conference Phone',
      'Yealink T42S Gigabit Business Phone',
      'Yealink T46S Gigabit Color Business Phone',
      'Yealink T46S Gigabit Color Business Phone with 2 Expansion Modules',
      'Yealink T46S Gigabit Color Business Phone with 1 Expansion Module',
      'Polycom VVX 150 Business IP Phone',
      'Polycom VVX 250 Business IP Phone',
      'Polycom VVX 350 Business IP Phone',
      'Polycom VVX 450 Business IP Phone',
      'Polycom VVX 450 Business IP Phone with 1 Expansion Module',
      'Yealink T48S Gigabit Color Touchscreen Business Phone with 2 Expansion Modules',
      'Yealink T48S Gigabit Color Touchscreen Business Phone with 1 Expansion Module',
      'Yealink T48S Gigabit Color Touchscreen Business Phone',
      'Yealink W60P Cordless Phone with 4 Handsets',
      'Yealink W60P Cordless Phone with 3 Handsets',
      'Yealink W60P Cordless Phone with 2 Handsets',
      'Yealink W60P Cordless Phone with 1 Handset',
      'Polycom OBi302 ATA',
      'Unify OpenScape Desk Phone CP700 with 2 Expansion Modules',
      'Unify OpenScape Desk Phone CP400 with 1 Expansion Module',
      'Unify OpenScape Desk Phone CP700 with 1 Expansion Module',
      'Unify OpenScape Desk Phone CP600 with 1 Expansion Module',
      'Unify OpenScape Desk Phone CP600 with 2 Expansion Modules',
      'Cisco CP8851 Gigabit Color Business Phone with 2 Expansion Modules',
      'Cisco CP8851 Gigabit Color Business Phone',
      'Cisco CP8851 Gigabit Color Business Phone with 1 Expansion Module',
      'Unify OpenScape Desk Phone CP700',
      'Cisco CP6821 Business IP Phone',
      'Unify OpenScape Desk Phone CP205',
      'Unify OpenScape Desk Phone CP400',
      'Unify OpenScape Desk Phone CP600',
      'Unify OpenScape Desk Phone CP100',
      'Unify OpenScape Desk Phone CP200',
      'Alcatel-Lucent 8008G Cloud Edition DeskPhone',
      'Yealink T57W Prime Business Phone',
      'Yealink T57W Prime Business Phone with 1 Expansion Module EXP50',
      'Yealink T57W Prime Business Phone with 2 Expansion Modules EXP50',
      'Alcatel-Lucent 8008 Cloud Edition DeskPhone',
      'Alcatel-Lucent 8018 Cloud Edition DeskPhone',
      'Alcatel-Lucent 8058s Cloud Edition Premium DeskPhone',
      'Alcatel-Lucent 8068s Cloud Edition Premium DeskPhone',
      'Polycom Trio 8300 Conference Phone',
      'Yealink T33G Gigabit Business Phone',
      'Yealink CP930W-Base Wireless DECT Conference phone',
      'Yealink W69P Cordless Phone with 1 Handset',
      'Poly CCX 400 Business Media Phone',
      'Poly CCX 500 Business Media Phone',
      'Poly CCX 600 Business Media Phone',
      'Poly CCX 700 Business Media Phone',
      'Yealink T53W Prime Business Phone',
      'Yealink T54W Prime Business Phone',
      'Yealink T43U Ultra-elegant Gigabit IP Phone',
      'Yealink T46U Ultra-elegant Gigabit IP Phone',
      'Yealink T48U Ultra-elegant Gigabit IP Phone',
      'Polycom IP 5000 Conference Phone - Rental',
      'Polycom IP 6000 Conference Phone - Rental',
      'Polycom VVX 501 Color Touchscreen Phone with 1 Expansion Module - Rental',
      'Polycom VVX 501 Color Touchscreen Phone - Rental',
      'Polycom IP 650 HD Executive IP phone with 3 Expansion Modules - Rental',
      'Polycom IP 650 HD Executive IP phone with 2 Expansion Modules - Rental',
      'Polycom IP 650 HD Executive IP phone with 1 Expansion Module - Rental',
      'Polycom IP 650 HD Executive IP phone - Rental',
      'Cisco 7841 Gigabit Business Phone - Rental',
      'Cisco 8861 Gigabit Color Business Phone - Rental',
      'Polycom Trio 8500 Conference Phone - Rental',
      'Polycom Trio 8800 Conference Phone - Rental',
      'Yealink T42S Gigabit Business Phone - Rental',
      'Yealink T46S Gigabit Color Business Phone - Rental',
      'Yealink T46S Gigabit Color Business Phone with 1 Expansion Module - Rental',
      'Yealink T46S Gigabit Color Business Phone with 2 Expansion Modules - Rental',
      'Polycom VVX 150 Business IP Phone - Rental',
      'Polycom VVX 250 Business IP Phone - Rental',
      'Polycom VVX 350 Business IP Phone - Rental',
      'Polycom VVX 450 Business IP Phone - Rental',
      'Polycom VVX 450 Business IP Phone with 1 Expansion Module - Rental',
      'Yealink T48S Gigabit Color Touchscreen Business Phone - Rental',
      'Yealink T48S Gigabit Color Touchscreen Business Phone with 1 Expansion Module - Rental',
      'Yealink T48S Gigabit Color Touchscreen Business Phone with 2 Expansion Modules - Rental',
      'Yealink W60P Cordless Phone with 1 Handset - Rental',
      'Yealink W60P Cordless Phone with 2 Handsets - Rental',
      'Yealink W60P Cordless Phone with 3 Handsets - Rental',
      'Yealink W60P Cordless Phone with 4 Handsets - Rental',
      'Polycom OBi302 ATA - Rental',
      'Unify OpenScape Desk Phone CP600 with 1 Expansion Module - Rental',
      'Unify OpenScape Desk Phone CP600 with 2 Expansion Modules - Rental',
      'Unify OpenScape Desk Phone CP400 with 1 Expansion Module - Rental',
      'Unify OpenScape Desk Phone CP700 with 1 Expansion Module - Rental',
      'Unify OpenScape Desk Phone CP700 with 2 Expansion Modules - Rental',
      'Cisco CP8851 Gigabit Color Business Phone - Rental',
      'Cisco CP8851 Gigabit Color Business Phone with 1 Expansion Module - Rental',
      'Cisco CP8851 Gigabit Color Business Phone with 2 Expansion Modules - Rental',
      'Unify OpenScape Desk Phone CP205 - Rental',
      'Unify OpenScape Desk Phone CP400 - Rental',
      'Unify OpenScape Desk Phone CP600 - Rental',
      'Unify OpenScape Desk Phone CP100 - Rental',
      'Cisco CP6821 Business IP Phone - Rental',
      'Unify OpenScape Desk Phone CP700 - Rental',
      'Unify OpenScape Desk Phone CP200 - Rental',
      'Yealink T57W Prime Business Phone - Rental',
      'Yealink T57W Prime Business Phone with 1 Expansion Module EXP50 - Rental',
      'Yealink T57W Prime Business Phone with 2 Expansion Modules EXP50 - Rental',
      'Polycom Trio 8300 Conference Phone - Rental',
      'Yealink T33G Gigabit Business Phone - Rental',
      'Yealink CP930W-Base Wireless DECT Conference phone - Rental',
      'Yealink W69P Cordless Phone with 1 Handset - Rental',
      'Poly CCX 400 Business Media Phone - Rental',
      'Poly CCX 500 Business Media Phone - Rental',
      'Poly CCX 600 Business Media Phone - Rental',
      'Poly CCX 700 Business Media Phone - Rental',
      'Yealink T53W Prime Business Phone - Rental',
      'Yealink T54W Prime Business Phone - Rental',
      'Yealink T43U Ultra-elegant Gigabit IP Phone - Rental',
      'Yealink T46U Ultra-elegant Gigabit IP Phone - Rental',
      'Yealink T48U Ultra-elegant Gigabit IP Phone - Rental',
    ]
  },
  "318~2": {
    "availablePhones": [
      'OBi302 ATA Refurbished',
      'Avaya IX IP Phone J139 - Refurbished',
      'Avaya IX IP Phone J179 - Refurbished',
      'Avaya IX Conference Phone B199 - Refurbished',
      'Avaya IX IP Phone J159 - Refurbished',
      'Avaya IX IP Phone J179 with JEM 24 Expansion Module - Refurbished',
      'Avaya IX IP Phone J179 with 2 JEM 24 Expansion Modules - Refurbished',
      'Avaya IX IP Phone J179 with 3 JEM 24 Expansion Modules - Refurbished',
      'OBi302 ATA',
      'Avaya IX IP Phone J139',
      'Avaya IX IP Phone J179',
      'Avaya IX Conference Phone B199',
      'Avaya IX IP Phone J159',
      'Avaya IX IP Phone J179 with JEM 24 Expansion Module',
      'Avaya IX IP Phone J179 with 2 JEM 24 Expansion Modules',
      'Avaya IX IP Phone J179 with 3 JEM 24 Expansion Modules',
      'OBi302 ATA - Rental',
      'Avaya IX IP Phone J139 - Rental',
      'Avaya IX IP Phone J179 - Rental',
      'Avaya IX Conference Phone B199 - Rental',
      'Avaya IX IP Phone J159 - Rental',
      'Avaya IX IP Phone J179 with JEM 24 Expansion Module - Rental',
      'Avaya IX IP Phone J179 with 2 JEM 24 Expansion Modules - Rental',
      'Avaya IX IP Phone J179 with 3 JEM 24 Expansion Modules - Rental',
      'Existing Phone',
      'Avaya Cloud Office for Desktop',
    ]
  },
  "324~1": {
    "availablePhones": [
      'OBi302 ATA Refurbished',
      'Avaya IX IP Phone J139 - Refurbished',
      'Avaya IX IP Phone J179 - Refurbished',
      'Avaya IX Conference Phone B199 - Refurbished',
      'Avaya IX IP Phone J159 - Refurbished',
      'Avaya IX IP Phone J179 with JEM 24 Expansion Module - Refurbished',
      'Avaya IX IP Phone J179 with 2 JEM 24 Expansion Modules - Refurbished',
      'Avaya IX IP Phone J179 with 3 JEM 24 Expansion Modules - Refurbished',
      'OBi302 ATA',
      'Avaya IX IP Phone J139',
      'Avaya IX IP Phone J179',
      'Avaya IX Conference Phone B199',
      'Avaya IX IP Phone J159',
      'Avaya IX IP Phone J179 with JEM 24 Expansion Module',
      'Avaya IX IP Phone J179 with 2 JEM 24 Expansion Modules',
      'Avaya IX IP Phone J179 with 3 JEM 24 Expansion Modules',
      'OBi302 ATA - Rental',
      'Avaya IX IP Phone J139 - Rental',
      'Avaya IX IP Phone J179 - Rental',
      'Avaya IX Conference Phone B199 - Rental',
      'Avaya IX IP Phone J159 - Rental',
      'Avaya IX IP Phone J179 with JEM 24 Expansion Module - Rental',
      'Avaya IX IP Phone J179 with 2 JEM 24 Expansion Modules - Rental',
      'Avaya IX IP Phone J179 with 3 JEM 24 Expansion Modules - Rental',
      'Existing Phone',
      'Avaya Cloud Office for Desktop',
    ]
  },
  "519~2": {
    "availablePhones": [
      'Polycom IP 5000 Conference Phone - Refurbished',
      'Polycom IP 6000 Conference Phone - Refurbished',
      'Polycom VVX 101 Basic IP Phone - Refurbished',
      'Polycom VVX 201 IP Phone - Refurbished',
      'Polycom VVX 311 Gigabit Ethernet Phone - Refurbished',
      'Polycom VVX 411 Color Gigabit Ethernet Phone - Refurbished',
      'Polycom VVX 500 Color Touchscreen Phone - Refurbished',
      'Polycom VVX 501 Color Touchscreen Phone - Refurbished',
      'Polycom VVX 601 Large Color Touchscreen Phone - Refurbished',
      'Polycom Trio 8500 Conference Phone - Refurbished',
      'Polycom Trio 8800 Conference Phone - Refurbished',
      'Polycom VVX 150 Business IP Phone - Refurbished',
      'Polycom VVX 250 Business IP Phone - Refurbished',
      'Polycom VVX 350 Business IP Phone - Refurbished',
      'Polycom VVX 450 Business IP Phone - Refurbished',
      'Polycom OBi302 ATA - Refurbished',
      'Unify OpenScape Desk Phone CP400 - Refurbished',
      'Unify OpenScape Desk Phone CP205 - Refurbished',
      'Unify OpenScape Desk Phone CP100 - Refurbished',
      'Unify OpenScape Desk Phone CP600 - Refurbished',
      'Unify OpenScape Desk Phone CP700 - Refurbished',
      'Unify OpenScape Desk Phone CP200 - Refurbished',
      'Polycom VVX 501 Color Touchscreen Phone with 1 Expansion Module',
      'Polycom IP 5000 Conference Phone',
      'Polycom IP 6000 Conference Phone',
      'Polycom VVX 501 Color Touchscreen Phone',
      'Polycom Trio 8500 Conference Phone',
      'Polycom Trio 8800 Conference Phone',
      'Polycom VVX 150 Business IP Phone',
      'Polycom VVX 250 Business IP Phone',
      'Polycom VVX 350 Business IP Phone',
      'Polycom VVX 450 Business IP Phone',
      'Polycom VVX 450 Business IP Phone with 1 Expansion Module',
      'Polycom OBi302 ATA',
      'Unify OpenScape Desk Phone CP700 with 2 Expansion Modules',
      'Unify OpenScape Desk Phone CP400 with 1 Expansion Module',
      'Unify OpenScape Desk Phone CP700 with 1 Expansion Module',
      'Unify OpenScape Desk Phone CP600 with 1 Expansion Module',
      'Unify OpenScape Desk Phone CP600 with 2 Expansion Modules',
      'Unify OpenScape Desk Phone CP700',
      'Unify OpenScape Desk Phone CP205',
      'Unify OpenScape Desk Phone CP400',
      'Unify OpenScape Desk Phone CP600',
      'Unify OpenScape Desk Phone CP100',
      'Unify OpenScape Desk Phone CP200',
      'Polycom Trio 8300 Conference Phone',
      'Polycom IP 5000 Conference Phone - Rental',
      'Polycom IP 6000 Conference Phone - Rental',
      'Polycom VVX 501 Color Touchscreen Phone with 1 Expansion Module - Rental',
      'Polycom VVX 501 Color Touchscreen Phone - Rental',
      'Polycom Trio 8500 Conference Phone - Rental',
      'Polycom Trio 8800 Conference Phone - Rental',
      'Polycom VVX 150 Business IP Phone - Rental',
      'Polycom VVX 250 Business IP Phone - Rental',
      'Polycom VVX 350 Business IP Phone - Rental',
      'Polycom VVX 450 Business IP Phone - Rental',
      'Polycom VVX 450 Business IP Phone with 1 Expansion Module - Rental',
      'Polycom OBi302 ATA - Rental',
      'Unify OpenScape Desk Phone CP600 with 1 Expansion Module - Rental',
      'Unify OpenScape Desk Phone CP600 with 2 Expansion Modules - Rental',
      'Unify OpenScape Desk Phone CP400 with 1 Expansion Module - Rental',
      'Unify OpenScape Desk Phone CP700 with 1 Expansion Module - Rental',
      'Unify OpenScape Desk Phone CP700 with 2 Expansion Modules - Rental',
      'Unify OpenScape Desk Phone CP205 - Rental',
      'Unify OpenScape Desk Phone CP400 - Rental',
      'Unify OpenScape Desk Phone CP600 - Rental',
      'Unify OpenScape Desk Phone CP100 - Rental',
      'Unify OpenScape Desk Phone CP700 - Rental',
      'Unify OpenScape Desk Phone CP200 - Rental',
      'Polycom Trio 8300 Conference Phone - Rental',
      'Existing Phone',
      'Unify Office for Desktop',
    ]
  },
  "537~1": {
    "availablePhones": [
      'Polycom IP 5000 Conference Phone - Refurbished',
      'Polycom IP 6000 Conference Phone - Refurbished',
      'Polycom VVX 101 Basic IP Phone - Refurbished',
      'Polycom VVX 201 IP Phone - Refurbished',
      'Polycom VVX 311 Gigabit Ethernet Phone - Refurbished',
      'Polycom VVX 411 Color Gigabit Ethernet Phone - Refurbished',
      'Polycom VVX 500 Color Touchscreen Phone - Refurbished',
      'Polycom VVX 501 Color Touchscreen Phone - Refurbished',
      'Polycom VVX 601 Large Color Touchscreen Phone - Refurbished',
      'Polycom Trio 8500 Conference Phone - Refurbished',
      'Polycom Trio 8800 Conference Phone - Refurbished',
      'Polycom VVX 150 Business IP Phone - Refurbished',
      'Polycom VVX 250 Business IP Phone - Refurbished',
      'Polycom VVX 350 Business IP Phone - Refurbished',
      'Polycom VVX 450 Business IP Phone - Refurbished',
      'Polycom OBi302 ATA - Refurbished',
      'Unify OpenScape Desk Phone CP400 - Refurbished',
      'Unify OpenScape Desk Phone CP205 - Refurbished',
      'Unify OpenScape Desk Phone CP100 - Refurbished',
      'Unify OpenScape Desk Phone CP600 - Refurbished',
      'Unify OpenScape Desk Phone CP700 - Refurbished',
      'Unify OpenScape Desk Phone CP200 - Refurbished',
      'Polycom VVX 501 Color Touchscreen Phone with 1 Expansion Module',
      'Polycom IP 5000 Conference Phone',
      'Polycom IP 6000 Conference Phone',
      'Polycom VVX 501 Color Touchscreen Phone',
      'Polycom Trio 8500 Conference Phone',
      'Polycom Trio 8800 Conference Phone',
      'Polycom VVX 150 Business IP Phone',
      'Polycom VVX 250 Business IP Phone',
      'Polycom VVX 350 Business IP Phone',
      'Polycom VVX 450 Business IP Phone',
      'Polycom VVX 450 Business IP Phone with 1 Expansion Module',
      'Polycom OBi302 ATA',
      'Unify OpenScape Desk Phone CP700 with 2 Expansion Modules',
      'Unify OpenScape Desk Phone CP400 with 1 Expansion Module',
      'Unify OpenScape Desk Phone CP700 with 1 Expansion Module',
      'Unify OpenScape Desk Phone CP600 with 1 Expansion Module',
      'Unify OpenScape Desk Phone CP600 with 2 Expansion Modules',
      'Unify OpenScape Desk Phone CP700',
      'Unify OpenScape Desk Phone CP205',
      'Unify OpenScape Desk Phone CP400',
      'Unify OpenScape Desk Phone CP600',
      'Unify OpenScape Desk Phone CP100',
      'Unify OpenScape Desk Phone CP200',
      'Polycom Trio 8300 Conference Phone',
      'Polycom IP 5000 Conference Phone - Rental',
      'Polycom IP 6000 Conference Phone - Rental',
      'Polycom VVX 501 Color Touchscreen Phone with 1 Expansion Module - Rental',
      'Polycom VVX 501 Color Touchscreen Phone - Rental',
      'Polycom Trio 8500 Conference Phone - Rental',
      'Polycom Trio 8800 Conference Phone - Rental',
      'Polycom VVX 150 Business IP Phone - Rental',
      'Polycom VVX 250 Business IP Phone - Rental',
      'Polycom VVX 350 Business IP Phone - Rental',
      'Polycom VVX 450 Business IP Phone - Rental',
      'Polycom VVX 450 Business IP Phone with 1 Expansion Module - Rental',
      'Polycom OBi302 ATA - Rental',
      'Unify OpenScape Desk Phone CP600 with 1 Expansion Module - Rental',
      'Unify OpenScape Desk Phone CP600 with 2 Expansion Modules - Rental',
      'Unify OpenScape Desk Phone CP400 with 1 Expansion Module - Rental',
      'Unify OpenScape Desk Phone CP700 with 1 Expansion Module - Rental',
      'Unify OpenScape Desk Phone CP700 with 2 Expansion Modules - Rental',
      'Unify OpenScape Desk Phone CP205 - Rental',
      'Unify OpenScape Desk Phone CP400 - Rental',
      'Unify OpenScape Desk Phone CP600 - Rental',
      'Unify OpenScape Desk Phone CP100 - Rental',
      'Unify OpenScape Desk Phone CP700 - Rental',
      'Unify OpenScape Desk Phone CP200 - Rental',
      'Polycom Trio 8300 Conference Phone - Rental',
      'Existing Phone',
      'Unify Office for Desktop',
    ]
  }
}