trigger PackageTrigger on Package__c (before insert, before update, after insert, after update) {

    new Triggers()
            .bind(Triggers.Evt.beforeinsert, new PackageTriggerHandler.CopyEngageFieldsFromAccount())
            .bind(Triggers.Evt.beforeinsert, new PackageTriggerHandler.UpdateARPUOnTechnicalPackages())
            .bind(Triggers.Evt.beforeinsert, new PackageTriggerHandler.PopulateInContactFieldsFromParentAccount())
            .bind(Triggers.Evt.beforeinsert, new PackageTriggerHandler.PopulatePackageMRRFields())
            .bind(Triggers.Evt.beforeinsert, new PackageTriggerHandler.PopulateServiceRelatedFields())
            .bind(Triggers.Evt.beforeupdate, new PackageTriggerHandler.UpdateARPUOnTechnicalPackages())
            .bind(Triggers.Evt.beforeupdate, new PackageTriggerHandler.CopyEngageFieldsFromAccount())
            .bind(Triggers.Evt.beforeupdate, new PackageTriggerHandler.PopulateInContactFieldsFromParentAccount())
            .bind(Triggers.Evt.beforeupdate, new PackageTriggerHandler.PopulatePackageMRRFields())
            .bind(Triggers.Evt.beforeupdate, new PackageTriggerHandler.PopulateServiceRelatedFields())
            .bind(Triggers.Evt.afterinsert, new PackageTriggerHandler.SendElaDataToNGBS())
            .bind(Triggers.Evt.afterinsert, new PackageTriggerHandler.CopyFieldsFromAccount())
            .bind(Triggers.Evt.afterinsert, new PackageTriggerHandler.ConnectServiceAccountToOrder())
            .bind(Triggers.Evt.afterupdate, new PackageTriggerHandler.ConnectServiceAccountToOrder())
            .bind(Triggers.Evt.afterinsert, new PackageTriggerHandler.SyncEnabledLBOOnQuote())
            .bind(Triggers.Evt.afterupdate, new PackageTriggerHandler.SyncEnabledLBOOnQuote())
            .bind(Triggers.Evt.afterupdate, new PackageTriggerHandler.UpdateReportedMRSOnTechnicalPackages())
            .bind(Triggers.Evt.afterinsert, new PackageTriggerHandler.UpdateReportedMRSOnTechnicalPackages())
            .bind(Triggers.Evt.afterupdate, new PackageTriggerHandler.UpdateServiceMRRFieldsOnAccount())
            .bind(Triggers.Evt.afterinsert, new PackageTriggerHandler.CopyContactCenterServiceFieldsToMasterAccount())
            .bind(Triggers.Evt.afterupdate, new PackageTriggerHandler.CopyContactCenterServiceFieldsToMasterAccount())
            .bind(Triggers.Evt.afterinsert, new PackageTriggerHandler.UpdateAccountFieldsFromBAP())
            .bind(Triggers.Evt.afterupdate, new PackageTriggerHandler.UpdateAccountFieldsFromBAP())
            .bind(Triggers.Evt.afterinsert, new PackageTriggerHandler.CreateCaseForManualProvisioningMPUB())
            .bind(Triggers.Evt.afterinsert, new PackageTriggerHandler.ActivateNewestOrders())
            .bind(Triggers.Evt.afterupdate, new PackageTriggerHandler.ActivateNewestOrders())
            .bind(Triggers.Evt.afterinsert, new PackageTriggerHandler.PopulateIsRingCxFieldOnMasterAccount())
            .bind(Triggers.Evt.afterupdate, new PackageTriggerHandler.PopulateIsRingCxFieldOnMasterAccount())
            .bind(Triggers.Evt.afterinsert, new PackageTriggerHandler.UpdateMarketingAttributionFields())
            .bind(Triggers.Evt.afterupdate, new PackageTriggerHandler.UpdateMarketingAttributionFields())
            .bind(Triggers.Evt.afterinsert, new PackageTriggerHandler.UpdateAccountDateFields())
            .bind(Triggers.Evt.afterupdate, new PackageTriggerHandler.UpdateAccountDateFields())
            .bind(Triggers.Evt.afterinsert, new PackageTriggerHandler.PopulatePackageForRelatedProSerQuotes())
            .bind(Triggers.Evt.afterinsert, new PackageTriggerHandler.CreateProservProjectAndPSIntegration())

            //.bind(Triggers.Evt.afterupdate, new PackageTriggerHandler.CreateImplementation())
            //.bind(Triggers.Evt.afterinsert, new PackageTriggerHandler.CreateImplementation())
            .manage();
}