global virtual class SpringCMItem {
    
        //global virtual List<Object> Items { get; set; }

        global string Href { get; set; }

        global long Offset { get; set; }

        global long ItemLimit { get; set; }

        global string First { get; set; }

        global string Previous { get; set; }

        global string Next { get; set; }

        global string Last { get; set; }

        global long Total { get; set; }
}