var staticResourceArr = new Array(
"Recommended Bluetooth Headsets and Speakers to Use with RingCentral",
"How Do I Send Faxes Using My Email?",
"Recording a greeting over the Phone",
"Setting up the RingCentral Service to Answer with Voicemail all of the time",
"RingCentral account privacy",
"Canceling a RingCentral Subscription",
"RingCentral Greeting Types",
"Updating Credit Card Information",
"How Long are Voicemails Stored on the RingCentral System?",
"Are There Any Limitations on Call Recording File Size and Storage?",
"Videos on the RingCentral App for the Android",
"Using Bluetooth Devices with iPhone App",
"Methods of Sending Faxes",
"Print to Fax",
"I don't like my Toll-Free number. Can I pick a new one?",
"Acquiring a RingCentral Local Number",
"Transferring an existing toll-free number (TFN) into RingCentral",
"Using Pre-existing Phone Numbers with RingCentral",
"Importing existing Microsoft &#174; Office Outlook &#174; Contacts into an Online RingCentral Contacts List",
"Free Minutes During 7-Day Trial",
"Enabling Ring Back Tones",
"Will my callers get a busy signal?",
"Keeping Phone Numbers of Cancelled Accounts",
"How long does the free trial last?",
"Upgrading and Downgrading to a Different RingCentral Service Plan",
"Requesting a toll-free vanity number",
"Setting Your RingCentral Phone Number to Receive Faxes",
"As an Administrator, can I change my Account or Extension Name?",
"New message notification",
"Printing faxes from my RingCentral Online Account",
"Changing Your RingCentral Online Account Password",
"Forwarding to/From RingCentral numbers: Rules and limitations",
"Sending Faxes using the Call Controller",
"Converting a .PDF fax to edit and resend",
"Viewing Favorites: Blackberry App",
"Viewing the Call Log on Blackberry App",
"Adding Favorites: Blackberry App",
"Viewing Contacts: Blackberry App",
"Frequently Asked Questions: Number Transfer Request",
"Adding Contacts: Blackberry App",
"Checking Messages: Blackberry App",
"CCAF - Credit Card Authorization Form",
"International Rates",
"Android App: Call Logs Do Not Sync",
"Updating the Call Controller",
"Troubleshooting the Android App: Cannot listen to Voice Messages",
"Checking for the Version of the Application on your Android",
"Supported Features on the RingCentral Android App",
"Tips to Speed up the Number Transfer Process",
"Polycom IP Phone User Guides",
"Logging out from RingCentral Account on an Android",
"Changing RingOut Options on an Android",
"Do-Not-Disturb Feature on an Android",
"Disabling the Connect Prompt on an Android",
"Android App: Messages (Voice Mails and Faxes)",
"Changing the Caller ID Settings on an Android",
"Adding New Numbers for RingOut on an Android",
"On Call Actions - Transferring a Call to Another Phone Number",
"VoIP services",
"Using RingCentral as a virtual calling card",
"Messages - Viewing Fax Messages from the Online Panel",
"On Call Actions - Transferring a Call to another extension",
"On Call Actions - Putting Call On Hold",
"Choosing online fax over fax machines",
"Using ##: Transfer call to a RingCentral quick dial using the Call Controller",
"My business is growning and I need new office phone lines",
"Using ##: Transfer a call to another phone number",
"Downloading Voice or Fax Messages to Your PC",
"Cancelling a fax scheduled to be sent",
"Using ##: Put a caller on Hold",
"Sending a Fax Online Using FaxOut",
"Internet Fax Settings",
"Sending a fax by e-mail",
"Adding a document to a fax from Microsoft Applications",
"Enabling individual extensions",
"Small business phone lines.",
"Messages - Listening to Voice Messages from the Online Panel",
"Using ##: Transfer call to a RingCentral extension",
"Music On Hold - Importing pre-recorded Music (in .wav format)",
"E-mailing Call Logs on a Set Schedule",
"Audio Tuning Wizard",
"Setting-up Multi-level extensions",
"Configuring International Call Settings",
"Where was that Audio Tuning wizard again?",
"Changing Your Security Question",
"Messages - Listening to Voice Messages from a Telephone",
"Updating Your Name and Personal Information",
"Changing Your Time Zone",
"Purchasing calling credit minutes",
"Changing the Name of a Greeting",
"Recording greetings from a PC via a Microphone",
"Clearing records from the Call Log",
"Music on Hold - Basic Setup",
"Changing a RingCentral number to receive faxes only",
"Setting Music on Hold to Silence Mode",
"Adding a RingCentral Phone Number",
"Importing greetings (.wav format)",
"Pointing a RingCentral number directly to an extension",
"Call Log Delivery",
"Extension Permissions",
"Deactivating extensions on a Mobile account",
"Call Log - Vicinity Map",
"Recording Voicemail Greeting",
"Activating a company directory",
"Recording your name used in Greetings over the phone",
"Disabling Do Not Disturb from Online Account",
"Sending inbound calls straight to cellphone",
"Sending inbound calls straight to voicemail",
"Creating a Directory Menu with Submenu",
"Cisco SIP IP Phone 7960: Initialization Process",
"Call Controller to Ring Instead of IP Phone",
"DigitalLine Troubleshooting: Linksys Router",
"Motorola VT2442 Voice Gateway: Before Installation",
"Interactive Voice Response",
"SoundPoint IP/SoundStation IP phones: Audio and Security Features",
"Saving a Sent File Confirmation",
"Adjusting the Volume",
"Using a Polycom Conference Phone with RingCentral",
"Configuring the SoundPoint IP/Soundstation IP Phones",
"Using my Own VoIP Phone Instead of the Call Controller",
"Headset Jack Size for Polycom SoundPoint IP 321 - VoIP Phone",
"RingCentral ATA and IP Phones",
"Creating Conference Calls using the Polycom SoundPoint IP 550 Phone",
"Voicemail: Polycom SoundPoint IP 550 Phone",
"Call Lists: Polycom SoundPoint IP 550 Phone",
"Muting the Microphone of the Polycom IP 550 Phone",
"Headset Jack Size of Polycom SoundPoint IP 335 - VoIP Phone",
"Adjusting Speaker Volume: Polycom IP 550 Phone",
"Placing a Call Using Polycom IP 550 Phone’s Optional Headset",
"Redialing on the Polycom IP 550 Phone",
"Answering a Call using the Polycom SoundPoint IP 550 Phone",
"Ending a Call on the Polycom IP 550 Phone",
"Placing Call Using Polycom IP 550 Phone’s Hands-Free Speakerphone",
"Do Not Disturb Function of the Polycom SoundPoint IP 550 Phone",
"Transferring a Call Using the Polycom SoundPoint IP 550 Phone",
"Placing a Call on Hold on the Polycom IP 550 Phone",
"How do I Change the Name of my IP Phone?",
"Forwarding Rules: Polycom IP 550 phone set up",
"Volume Control of the Soundpoint IP 321/335",
"Voice Quality: Polycom SoundPoint IP 550 Phone",
"Installation: Polycom SoundPoint IP 550 Phone",
"New Feature- Call Recording on Demand",
"Package contents: Polycom SoundPoint IP 550 Phone",
"Firewall Ports Installation: Polycom IP 550 Phone",
"Do Not Disturb Function on the Soundpoint IP 321/335",
"Ending Calls on the Soundpoint IP 321/335",
"Attended Transfer Function on the Soundpoint IP 321/335",
"Answering Calls on the Soundpoint IP 321/335",
"Hosting Conference Calls on the Soundpoint IP 321/335",
"Call Lists on the Soundpoint IP 321/335",
"The RingCentral Referral Program",
"Using RingOut from an Online Account",
"Soundpoint IP 321/335 Installation",
"Placing Calls Using Soundpoint IP 321/335",
"Firewall Ports Installation: Polycom Soundpoint 321/335",
"Speed Dialing using Soundpoint IP 321/335",
"Voice Quality: Polycom Soundpoint 321/335",
"Redialing Numbers Using Soundpoint IP 321/335",
"Polycom Soundpoint 321/335: Package Contents",
"Making changes to a phone’s name, extensions, etc.: Polycom Soundpoint 321/335",
"Web Settings: Auto Delete Voicemail and RingCentral Voicemail Player",
"Recording Company Greeting over the phone",
"Ordering professional voice talents to record greetings",
"Call Log - Deleting a Specific Call",
"Creating Company Level Main Greeting",
"Voicemail Options",
"Call Forwarding",
"How RingOut works",
"How RingOut Calls are Billed",
"Phone Numbers you can Dial from Ringout",
"RingCentral Refund Process",
"All About Minutes and Calling Credits",
"Charges for Checking Messages or Recording Greetings Over-the-Phone using your Toll-Free Number",
"The Call Controller Software",
"Troubleshooting the Call Controller Software",
"Using RingOut to Dial from a Microsoft Office Outlook Contacts List",
"Uninstalling and Disabling the Call Controller software",
"Downloading the Call Controller to Multiple Computers",
"Conferencing Two Lines from Softphone",
"Viewing Blocked/Allowed Numbers",
"Fax Cover Page Issue: FaxOut",
"Polycom Device Upgrade Process",
"Voicemail Messages - Downloading",
"Fax Cover Page Issue: Fax via e-mail",
"Fax Messages - Downloading",
"Disabling Company Greeting",
"Unblocking a Number I blocked before",
"Viewing Blocked Numbers",
"RingCentral Online Account",
"My Settings Page - Interactive Demo",
"Download Page - Interactive Demo",
"RC Office - Compare Plans",
"RingCentral Community Forum",
"Contacts Page - Interactive Demo",
"RingCentral Online Account - Forgotten Password",
"Using Analog Phones and Devices with RingCentral Service",
"Customer Support is Asking for a Screen Capture of Error/s: Windows XP/Office 2003/Outlook Users",
"Call Log Page - Interactive Demo",
"Custom Notification for Call Recording",
"Overview Page - Interactive Demo",
"Messages Page - Interactive Demo",
"Customer Support is Asking for a Screen Capture of Error/s: Mac OS X Users",
"Interactive Screen Shots/Demos",
"Faxes: How to Transmit Directly via Internet",
"Company Directory - Searching by Name",
"Urgent Message Notification - Enable Do Not Disturb (DND)",
"How Do I Set the Call Controller to Send Faxes via Email as an Attachment?",
"Turn Off Company Directory feature",
"Setting Company Directory Access Number",
"Transferring Calls Between Quick-Dial Numbers",
"Call Flip",
"Activating multiple extensions",
"New Message Notification on the Call Controller",
"What is the RingCentral Affiliate Program",
"RingCentral Affiliate Program - Requirements",
"Does RingCentral Have an Affiliate Program?",
"Status of Fax Documents",
"New Call Notification on the Call Controller",
"Where can I learn more about the RingCentral Affiliate Program?",
"How to Identify Incoming Calls as Being from My RingCentral Number - DNIS",
"Call Controller Notification",
"Enabling Call Controller Notification",
"Benefits of an 800 Number",
"Adopting an Online Fax Service",
"Virtual and Traditional PBX",
"Disabling Call Controller Notification",
"Benefits of 1 800 Numbers to Frequent Flyers?",
"Keeping Track of the Consumed Minutes for the Account",
"Extending Billing Date for Additional Features",
"Using Default Voicemail Greeting via Web",
"Importing a Custom Voicemail Greeting via Web",
"RC Mobile Plans",
"Changing the Security Question and Answer via Web",
"Changing Company Name via Web",
"Changing Contact Phone Numbers via Web",
"Clearing/Deleting Call Logs",
"Updating Email Address",
"Changing Extension Password via Web",
"Setting Business Hours via the Online Account",
"Receiving Call Logs via Email",
"Changing Caller ID Name via Web",
"Changing the Time Zone via the Web",
"Setting Business Hours",
"Call Log - Blocking Individual Phone Number",
"Message Settings: Text Alert for Missed Incoming Calls",
"Message Settings: Text Alert to Mobile when Messages Arrive",
"Editing Personal Contact Informations",
"RingCentral Mobile - Retrieving Messages for different extension",
"Call Log - Quick Call Back",
"Easy Online Contact Searching",
"RingCentral Mobile - International Calls",
"RingCentral Mobile - Retrieving Messages",
"Deleting Personal Contacts",
"RingCentral Mobile - Unopened Messages",
"Secure Faxing",
"Exporting my Address Book from Microsoft Outlook Express",
"Downloading RingCentral Mobile",
"RingCentral Mobile and RingCentral Account",
"RingCentral Mobile - Supported Platforms",
"RingCentral Mobile Fees",
"How to Send a Message From Your RingCentral Online Account",
"RingCentral Mobile - Logging On",
"Forwarding faxes",
"RingCentral Mobile - Call Logs",
"RingCentral Mobile - Speed Dial Contacts",
"Launching Internet Fax",
"Forwarding Calls (Call Diversion) Sequentially in a Fixed Order",
"Exporting Contacts from Microsoft Office Outlook",
"Attaching Fax Documents",
"Adding Fax Recipients",
"Scheduling Fax Delivery",
"Steps in Preparing Text-to-Speech",
"Downloading and saving faxes from my RingCentral Online Account",
"Adding a Cover Page Note",
"Forwarding Calls Sequentially(Call Diversion) in a Rotating Order",
"Viewing Call Logs",
"Can I See Messages I Have Deleted in the Online Account?",
"How to Disable the Account Security Confirmation?",
"Can I See my Recent Messages via my Online Account?",
"Changing My Service Plan",
"Provisioning a 3rd party Linksys Device",
"Account Access Confirmation",
"Viewing Recent Calls via the Online Account",
"Enabling / Disabling Account Access Confirmation as an Extension User",
"Giving Feedback via the Web",
"Getting Started",
"Adding Departments using the iPhone",
"Adding User Extensions using the iPhone",
"Email to Fax Limitations",
"Alternate Number?",
"Can I Change my RingCentral UK (formerly BT RingCentral) Phone Number?",
"How Do I Login to My Primary Account/Extension?",
"Can I Show My Company Name on Outbound Calls?",
"Provisioning a Polycom Phone",
"How Many Minutes Come with the Trial?",
"Mobile Plan User Guide",
"Which Credit Card Will Be Used to Make My Next Payment?",
"Assisted Provisioning of 3rd Party Devices",
"What are the Limitations for Sending Faxes via FaxOut?",
"DNIS",
"Do You Have an Application for my iPhone?",
"FaxOut Limitations?",
"How Long Will My Recorded Calls Be Stored?",
"New MAC Softphone Dialing Option: Softphone or RingOut",
"How to Copy an Existing Greeting from One Extension and Insert It into Another Extension",
"RingCentral Mobile Plan Minutes",
"MAC Softphone New Feature",
"MAC Softphone Text to Speech Feature",
"Caller ID: Identifying Calls Received on a Mobile Phone",
"Setting up Multiple Companies in One RingCentral Account?",
"Forwarding Calls Manually on MAC Softphone",
"Upload Greetings in Standard Browsers",
"Professional Greetings",
"Music on Hold Significance",
"Setup Fees",
"Free Trial",
"Hotkeys?",
"Record Phone Calls",
"Maximum Mailboxes/Extensions",
"Simultaneous Number Forwarding",
"Fax Account Storage",
"Recorded Calls Default File Format",
"Getting an RMA",
"RingMe Click-to-Call",
"Call Controller Quick Link Icons - Messages",
"Headsets and softphones",
"Call Controller Quick Link Icons - Online Account",
"Vista/Windows 7-64 bit Operating System - Compatibility with RingCentral Call Controller",
"Say goodbye to telemarketers!",
"Call Controller Quick Link Icons - Call Logs",
"Call Controller Quick Link Icons - Faxing",
"Call Controller Quick Link Icons - Contacts Directory",
"Internet faxing",
"Auto Attendant",
"Opening doors using a toll-free number",
"RingCentral Mobile and the iPhone",
"Enabling Do Not Disturb",
"Maintaining Communications",
"Voicemail Player",
"Extension Speed Dial",
"Automatic Outlook Contacts Synchronization",
"Affordable advertising",
"Text-to-Speech",
"Refund Amounts for cancelled accounts",
"Sending and Receiving Faxes from a Fax Machine",
"PBX setup via RingCentral",
"Pressing the Scan button in Call Controller",
"TIFF attachments in inverted colors",
"Forgot the Answer to the Security Question",
"Set up a Security Question",
"VoIP perks",
"RingCentral: Never leave your office",
"Advantages of IP phones",
"Communicating efficiently with PBX",
"Hotkey F6 in Call Controller",
"RingCentral and my business",
"Searching for Answers",
"Improving team communications",
"Using older versions of Call Controller",
"Checking Call Controller version",
"Updating Call Controller",
"Establishing a professional image using RingCentral",
"Plug and ring simplicity with RingCentral",
"Balancing work and family with RingCentral",
"Startups and Communications Systems",
"Using the Linksys IP Phone for the First Time",
"How to enable/disable Call Controller options",
"Maximize Voicemail",
"Internet Fax - File Attachments",
"RingCentral as the perfect small-business partner",
"IP Phone is adapter-free",
"RC Office - Going Virtual",
"Advantages of Toll-Free Numbers",
"Installing ATA Adapter",
"Benefits of ensuring QoS",
"CVV - Card Verification Value",
"Issues after installation of a new device: What to do",
"RingCentral Payment Methods",
"Call Controller Program and Data Files",
"Disable and/or Delete an Extension",
"QoS",
"Ports and Firewalls",
"RingCentral Compliance and Administrative Recovery Fee",
"Tool for Evaluating Network Performance",
"Non geo number",
"How to create and enable an extension",
"RingCentral Office 30-Day Money Back Guarantee",
"Tips for Dealing with Network Quality Issues",
"eXtreme Fax",
"Fax machines and eXtreme Fax",
"Advantages of eXtreme Fax",
"RingCentral Office",
"Freephone number",
"Clearing Browser Cache and Cookies",
"Changing the Local Port on the Call Controller",
"Analog Telephone Adapter",
"Power-Cycling a Device",
"Free Fax Software",
"Billing History",
"Dedicated Fax",
"Fax Broadcasting",
"Static IP Address",
"Account Status",
"Printing faxes automatically from the Call Controller",
"Messages in Deleted Items Folder in Call Controller",
"Recording a Greeting - Troubleshooting",
"Reasonable Use Policy Changes: Changes to Annual Plan",
"Cover Page - Linking an Object",
"Personalizing the Online Interface with a Logo",
"SIP Server Connection",
"Issues with Specific Fax Machines",
"Uploading Ring Tone/Music",
"Transferring a Phone Number for eXtreme Fax",
"Configuring Business Hour Answering Rule to Ring a Number Only",
"SPA900 Series IP Phones: LCD Display & Keypad Controls",
"SPA941: Features & Ports",
"SPA900 Series: Attaching the Desk Stand & Mounting",
"Tell a Friend",
"Configure Business Hour Answering Rule to take messages only",
"SPA921: Features & Ports",
"SPA962: Features & Ports",
"Accessing the Linksys 900 series phone admin web server",
"Power over Ethernet (PoE)",
"Network Address Translation",
"SPA900 Series IP Phone: Caring for the Devices",
"SPA900 Series: Ports and Features",
"Transferring Calls on the Polycom SoundStation IP 6000",
"Redialing numbers on the Polycom SoundStation IP 6000",
"Editing a contact on Your Polycom SoundStation IP 6000",
"Hosting Conference Calls on the Polycom SoundStation IP 6000",
"Speed dialing on the Polycom SoundStation IP 6000",
"Holding and resuming calls on the Polycom SoundStation IP 6000",
"Adding a contact directory of the Polycom SoundStation IP 6000",
"Speaker and ringer volume of the Polycom SoundStation IP 6000",
"Searching for a contact on your Polycom SoundStation IP 6000",
"Muting the microphone of your Polycom SoundStation IP 6000",
"Ending calls on the Polycom SoundStation IP 6000",
"Answering calls on the Polycom SoundStation IP 6000",
"Placing calls on the Polycom SoundStation IP 6000",
"Polycom SoundStation IP 6000: Installation – Voice Quality:",
"RingOut API",
"Creating Custom Answering Rules Similar to FollowMe",
"Calling into IVRs Without Conflicting with RingCentral Features",
"Polycom SoundStation IP 6000",
"Polycom SoundStation IP 6000 Installation",
"FaxOut API or Send Fax Web API",
"Polycom SoundStation IP 6000: Installation - AC Powera",
"Forwarding Rules: Setting up the Polycom SoundStation IP 6000",
"Firewall Ports installation - Polycom SoundStation IP 6000",
"Choosing a Cover Page",
"RingOut Caller ID Settings",
"Changing the Contact Number",
"Downloading Mobile Applications via the Web",
"Deleting a Trusted Email Address.",
"Changing Passwords",
"Changing the User Name",
"Changing the Contact Email Address",
"Caller ID Name (CNAM) Settings",
"Adding a Trusted Email via the Web",
"Delivering Department Voicemails to another Extension",
"Customizing Business Hours for Departments",
"Importing a Department Voicemail Greeting via the Web",
"Call Handling: Sequential Ringing Option",
"After Hours Call Handling for Departments",
"Changing the Department Voicemail Greeting via the Web",
"Recording a Department Voicemail Greeting Over the Phone",
"Notification Settings for a Department Manager via Web",
"Forward Calls from an Existing Phone Number using an iPhone",
"Transfer/Port in Phone Numbers using an iPhone",
"Uploading a Department Custom On-hold Music via the Web",
"On-hold Music",
"Creating a Fax Only Extension",
"Call Handling: Simultaneous Ringing Option",
"Checking Department Messages using an iPhone",
"Setting up Call Handling for Departments via Online Account",
"Viewing the Department Call Logs using an iPhone",
"Call Handling: Rotating Ringing Option",
"Recording Department Greeting over the Phone",
"Activating/Deactivating Department Greetings",
"Adding a Company Fax Number using an iPhone",
"Assigning the Operator Extension",
"Auto-Receptionist Call Handling - Disconnect Option",
"Changing Department Information",
"Adding Local Company Number using an iPhone",
"Assigning/Changing Department Members via Web",
"Changing the Area Code when Selecting a New Number",
"Adding a Direct Numbers using an iPhone",
"Sending Calls Directly to an Extension via the Web",
"Directing Calls to the Operator When No Extension is Selected",
"Enabling/Disabling Do Not Disturb using the iPhone App",
"Setting Up Department Greeting",
"Adding Local Company Numbers",
"Using RingOut on an iPhone",
"Editing Department Information via the Web",
"Checking Messages - iPhone",
"Viewing Contacts Using an iPhone",
"Redirecting my Calls Received from my Phone Number to my Online Account",
"Viewing the Call Log using an iPhone",
"Inbound Calls Forwarded Outside US",
"Clearing the Browser Cache & Cookies",
"Changing Ring Tones and Music on Hold via Call Controller",
"Operating System",
"Extensions Structure",
"Outlook Integration",
"Calling Card",
"Call Controller Minimum Requirements",
"Tell a Friend Reward Program",
"What is RingMe?",
"RingCentral as the new way to manage business communications?",
"Attaching a Corrupt File in Fax",
"Outbound VoIP option with DigitalLine",
"Delivery of voicemail and faxes to the Administrator's mailbox",
"Real-Time Call Control",
"Advantages of Answering Rules",
"Do I immediately get my own toll-free phone number?",
"Setup New Audio Equipment - Headset or Microphone",
"Call Screening",
"What is Click-to-Call Out?",
"DigitalLine",
"Enabling the Dial-By-Name Directory.",
"Digital Line Sound Quality",
"RingCentral Online Business Plus plan",
"Call Controller File Locations",
"Refund Charges",
"Uninstalling the Call Controller",
"Business Premium plan",
"Any Charges When Updating Credit Information?",
"Making the Call Controller ring repeatedly",
"Sending Faxes from Any Application",
"PDF",
"TIFF",
"Fax Broadcasting to Multiple Recipients",
"PBX or Private Branch Exchange",
"TFN or Toll Free Numbers",
"What is an ATA or an Analog Telephone Adapter?",
"Blocking Junk Faxes",
"Can I purchase phones without adding additional lines?",
"Commitment Period to RingCentral",
"Free Trial and Credit Card Charges",
"Account Activation",
"Setup Fees",
"Minutes Usage and Cost",
"RC Mobile and RC Office",
"Do I need a new phone line or special equipment?",
"Free Trial",
"Checking Messages: Charges",
"Keeping Toll-Free Numbers",
"Using my current number with RingCentral service",
"Estimated Shipping Times",
"What is RingCentral?",
"Using Current Phone Number with RingCentral Service",
"Special Equipment, Requirements for RingCentral Service",
"Account Administrator",
"Blocking Marketing Pieces from Fax Service",
"E911 Fee",
"Cost of RingCentral services",
"RingCentral Office Phones/Devices",
"RingCentral Office Setup",
"Using traditional fax machines with RingCentral fax service",
"RingCentral Office Features",
"Advantages of the Linksys SPA-942 over the Linksys SPA 941",
"Unlimited minutes and the Fair Usage Policy",
"Difference of Office and Mobile plans",
"RingCentral Office Activation",
"Posted numbers in Vistaprint website that are already taken",
"Federal Universal Service Fund charges",
"Using Devices Other Than Linksys IP Phones",
"Configuring voicemail",
"Can I call out if I subscribe to RingCentral Mobile only?",
"RingCentral's W-9 Form",
"Screening calls without an introductory greeting",
"Android app with RingCentral service on my Droid",
"RingCentral accounts are encrypted",
"BlackBerry App Availability",
"RingCentral Office",
"Polycom phones compatibility",
"Monitored Alarm Systems",
"Using Credit Card Machine with RingCentral service",
"Is There a BlackBerry App to Use with My RingCentral service?",
"Can I forward my saved Call Recordings to others?",
"Where can I find my saved Call Recordings?",
"Are callers informed when I use Call Recording?",
"What is Call Recording and how does it work?",
"Can I disable on-demand call recording?",
"Defective Equipment Return Policy",
"RingOut does not seem to work on my iPhone",
"RingOut calls on iPhone",
"Adding Direct Extension Numbers via the Web",
"Types of Phone Numbers",
"Using Pre-recorded Messages as Custom Company Greeting via the Web",
"Reassigning a Direct Extension Number to Another Extension",
"Recording a Customized Company Greeting over the Phone",
"Setting Company Business Hours via the Web",
"Creating a Custom Greeting via the Web",
"Adding a Company Fax Number via Web",
"Default Company Greeting Setup via the Web",
"Using RingOut via the Web",
"Overview - RingOut",
"Overview - Call Log Tab Info",
"Overview Tab - Web",
"Settings Tab - Administrator Features",
"Using the Mid-Call Move Feature",
"Overview - Messages Tab",
"Adding Departments",
"Default Department Greetings",
"Custom Department Greeting",
"Overview - Contacts Tab Info",
"Maximum Holding Time for Department Calls",
"Importing a Custom Introductory Greeting via Web",
"Extension User Overview",
"Department Manager",
"Enabling/Disabling the Audio Presentation Feature",
"Creating a Custom Voicemail Greeting - iPhone",
"Emailing Customer Service",
"Setting Default Voicemail Greeting - iPhone",
"Forwarding Phone Calls",
"Introductory Greeting",
"Maximum time callers can be on hold in a Department.",
"Control the types of messages each of your RingCentral telephone numbers can receive",
"Caller ID Number",
"Improving Phone Call Quality",
"Connect Prompt",
"Voicemail greeting",
"Phone Call Quality: What is VoIP Quality of Service?",
"Caller ID Name",
"Virtual Calling Card",
"E-Mail Address Used in Sending Faxes",
"Name Greeting",
"Maximum Greeting Durations",
"Transferring a Call - Caller Placed On Hold",
"Unavailable Greeting",
"Recording a Company Greeting Over the Phone",
"Placing a Caller On Hold",
"Announcement Greeting",
"Company Greeting",
"CAPTCHA confirmation for RingMe",
"One way audio with SNOM phones?",
"DigitalLine Phones work outside US?",
"RingCentral Support Phone Numbers",
"Dialing out to 0870, 0871 and other special-billing numbers",
"Audio Tuning Wizard",
"ATA Adapter Installation - PAP2T",
"Difference between Departments and Extensions",
"How calling credit balance and usage are affected when DigitalLine service Is added",
"RingMe Confirmation Code (CAPTCHA) Now Required",
"Fax Attachment Issues",
"Setting up several SoftPhones to answer inbound calls",
"Turning Off the Call Waiting Feature of the Linksys 921 or ATA DigitalLine Service",
"My RingCentral Call Controller icon does not appear in my PC system tray.",
"Solutions: Creating Custom Holiday and Vacation Answering Rules",
"My Administrator set up a Department and added me as a member. How do I set up my extension so I'm ready to take calls?",
"Reprinting Copies of Past Invoices",
"RingCentral Department Overview and Setup",
"Solutions: Supporting Multiple Fax Numbers in One RingCentral Account",
"How can I determine the geographic location of a phone number that called my RingCentral number?",
"Solutions: Password, PID and Area Code Routing",
"Federal Universal Service Fund Fee",
"Changing the Information on Fax Cover Sheets Sent from the Call Controller",
"Credit Card Authorisation form for RingCentral customers",
"Forwarding calls and dialing out to an international number",
"Password and Security Measures Keep Account Information Private",
"RingCentral User Guide",
"RingCentral Rate Matrix - Cost of Inbound and Outbound calls",
"Can I customize my own text-to-speech reply from the Call Controller?",
"RingCentral, Information, Organizations, Features, club, association, community",
"How do I send Faxes using my email?",
"Can I use my 3rd party Grandstream IP phone?",
"Viewing and Printing My Received Faxes",
"How can I use my own SNOM IP phone with RingCentral?",
"My DigitalLine (VoIP) phone is not connecting to RingCentral. What's wrong?",
"Polycom SIP telephones - Installation and Setup instructions",
"Synchronizing Microsoft Outlook Contacts with RingCentral Contacts",
"3rd party Cisco SIP telephones?",
"Can I forward/divert calls directly to an extension behind a telephone number?",
"Credit Card Authorization Form (CCAF)",
"The phone connected to my SPA 2102 ATA adapter is not working. How can I fix it?",
"Setting Default Department Greeting - iPhone",
"Can I make a 411 Directory Information call?",
"What do the Detailed Call Logs show?",
"Recording a Custom Department Greetings - iPhone",
"Call Handling Setup for Departments - iPhone",
"Keyboard Shortcuts for the Call Controller",
"Screening Callers with No Caller ID via Web",
"Can I give Administrative privileges to an extension?",
"Custom Voicemail Greeting for Departments - iPhone",
"If I downgrade my Service Plan, will I be credited for the unused portion of the previous plan?",
"Transferring a local number to RingCentral",
"eXtreme Fax Plans",
"Grandstream HandyTone ATAs - Installation and Setup instructions",
"DigitalLine User Guide and Frequently Asked Questions",
"Aastra SIP telephones - Installation and Setup instructions to connect on the RingCentral DigitalLine network",
"Viewing Received Faxes",
"Setting up Notification Settings via Web",
"Recommended Headsets for Softphone and other IP Phones",
"What is an Administrator?",
"Adding an E-mail Address to the Trusted Email Address List via Web",
"Default Voicemail Greeting for Departments - iPhone",
"Using RingOut -BlackBerry",
"Default Company Greeting using the iPhone App",
"Recording Custom Company Greeting - iPhone",
"Assigning Department Members using an iPhone",
"Assigning Operator Extension - iPhone",
"Department Manager Overview",
"Setting up a Company Greeting for Additional Numbers.",
"Fax Icon Missing on the Call Controller",
"Android App: Favorites",
"Android: Call Log Feature",
"Android App: Contacts",
"Using RingOut on Android",
"E-Mail Address Used in Sending Faxes",
"Changing from a Monthly to an Annual Plan",
"Refund for Cancelled Annual Plan Accounts",
"Ordering Call Forwarding",
"Billing Cycle: Your Next Billing Statement",
"Billing Information / Billing Statement",
"Call Recording Notifications",
"Adding RringMe to a Website",
"What is TWAIN?",
"Creating a Custom Fax Cover Page Using Call Controller",
"File Attachments Supported for Faxes",
"Direct Faxing from Scanner using the RingCentral Call Controller",
"Setting RingCentral Internet Fax as the Default Printer",
"Credit Card Authorization Form (CCAF) Information",
"Sending a Fax Directly from a Scanner using RingCentral E-Mail to Fax Feature",
"Enabling and Disabling Do Not Disturb",
"Recording Phone Calls/Conversation",
"Transferring a Call to Another Extension",
"Difference between Departments and Extensions",
"Using RingOut via Web",
"Recording a Custom Company Greeting over the Phone",
"Adding and Enabling an Extension",
"Voice Talents for Recorded Greetings",
"Caller ID Name",
"Forwarding Calls and Dialing Out to an International Number",
"Custom Greeting Description Title",
"Retrieving the IP Address of Linksys SPA 2102 (ATA)",
"Requesting a Toll-free Vanity Number",
"Settings for SIP-based Phones",
"Manual Provisioning of 3rd Party Devices",
"Assisted Provisioning of 3rd Party Devices",
"Retrieving the IP Address of Cisco Phones",
"Transferring an Existing Toll-free Number to RingCentral",
"Using SIP-based Phones with Your RingCentral Account",
"Transferring an Existing Local Number to RingCentral",
"Manual Provisioning: Linksys SPA 2102 (ATA) Devices",
"Checking the Version of the Call Controller",
"Manual Provisioning Polycom SIP-based Phones",
"Manual Provisioning Linksys/Cisco SIP-based Phones",
"Uninstalling the Call Controller on Windows XP",
"Sending Faxes using the Call Controller",
"Downloading the Call Controller",
"Troubleshooting the Call Controller",
"Sending Scheduled Faxes using the Call Controller",
"Setting the Call Controller to use RingOut",
"Retrieving the IP Address of Polycom Phones",
"Package Contents of Cisco SPA 525G",
"Adding Mid Call Move Numbers to your Extension",
"Mid-Call Move Numbers",
"Recording a Custom Voicemail Greeting over the Phone",
"Screening Calls via Web",
"Recording a Custom Introductory Greeting over the Phone",
"Call Log Delivery Setup",
"Sending Faxes from iPhone",
"Screening Callers Not in Contact list via Web",
"Powering Cisco SPA 525G",
"Items for Developers",
"Incoming Fax Notifications - iPhone",
"Fax Notification Settings - iPhone",
"Will the iPhone app also work on my iPad?",
"Extension Voicemail Notification via iPhone",
"Missed Call Notification Settings using an iPhone",
"Sent Fax Confirmation",
"PC Incoming Call Notification - Integration",
"Training Videos",
"Telephone Numbers for Customer Care",
"RingOut - iPhone",
"Changing Extension Numbers Using an iPhone",
"Changing Contact Email Address - iPhone",
"Voicemail Notification for an Administrator via iPhone",
"Blocking Calls with No Caller ID",
"Ring Duration for Forwarding Calls",
"Changing Extension Name - iPhone",
"Granting Administrative Privileges via the Web",
"Changing the Caller ID Settings using an iPhone",
"Missed Call Notification Settings",
"RingOut - iPhone",
"Playing Announcements",
"Unconditional Call Forwarding for After Hours Calls",
"Getting the Latest Version of Smartphone Applications",
"Caller ID Settings for Extensions",
"Scheduling Fax Messages via the Web",
"Changing Plans",
"iPhone App: Making Outbound Calls via VoIP/Wi-Fi",
"Creating a Messages Only Extension via the Web",
"Blocking Specific Phone Numbers",
"Changing Department Status over the Phone",
"Sending Faxes via the Web",
"Do Not Disturb Feature",
"Over the Phone Features",
"Using RingOut",
"Fax, Voicemail, and Missed Call Notification Settings",
"Viewing Received Faxes via the Online Account",
"Placing Outbound Calls using another Phone",
"Check Messages over the Phone",
"Company Directory",
"What bandwidth is needed for RingCentral DigitalLine service?",
"How do I upload files for the Music on Hold on my Call Controller?",
"Changing My E911 Dialing Address for my $digitalline Phone",
"Can I use ONE DigitalLine subscription to place calls simultaneously from Softphones on TWO computers?",
"What will I have to do to configure the SPA 921 IP phone when it arrives?",
"How do I change the SPA 921’s name, extension assignment, or other provisioning actions?",
"Is My Broadband Connection Sufficient to Support DigitalLine Service?",
"Shipping of DigitalLine Phone Ordered from an Online Account",
"Can I use my DigitalLine phone while I m on the internet on my computer",
"How do I make a Three-Way Conference Call on the SPA 921?",
"Solutions: How Real Estate Professionals use RingCentral",
"How do I transfer a call on the SPA 921?",
"How does Speed Dialing work in the Call Controller with Softphone?",
"Professionally Recorded Greetings",
"Can I select the Caller ID when making DigitalLine calls?",
"Solutions: Automatically routing calls to different offices by time of day",
"Can I route inbound calls based on the caller's location?",
"Application for Windows Mobile SmartPhones",
"Using an existing SIP-based VoIP phone with my RingCentral DigitalLine service",
"Solutions: Using RingCentral in tandem with an office receptionist",
"Allowing or restricting calls from Hawaii, Alaska, or Canada to a Toll-Free Number",
"Enabling a Sub-Group of Forwarded Phone Numbers to Ring Simultaneously",
"Microsoft Vista and Windows 7 Compatible Call Controller",
"How can I prevent unwanted telemarketing calls?",
"How do I set-up and use Quick-Dial to transfer calls?",
"Transferring a Call",
"Troubleshooting the Mac Call Controller",
"Troubleshooting Sending and Receiving Fax",
"Fax Broadcasting",
"How do I enable RingCentral RingMe",
"Adding RingMe into My Outlook Email Signature",
"Downloading the Call Controller for Mac",
"RingMe Code Options: Java Script vs. Non-Java Script",
"Add RingMe to an Outlook Express Email Signature",
"Supported File Attachments for Faxes",
"How do I set up RingMe?",
"Uploading Greetings/Music On Hold using Mac",
"Auto Attendant Greeting Options",
"Using Your Own Button/Image for RingMe",
"Sending Faxes Using E-mail",
"Adding RingMe to My Website",
"Sending Faxes to Toll Free Numbers",
"Can my RingCentral toll-free number answer calls from International locations?",
"RingCentral Forums",
"Creating a Custom Fax Cover Page Using the Call Controller",
"Call Controller with SoftPhone Overview Video",
"RingMe Information",
"Recording a Company Greeting Over the Phone",
"Why don't I see Music On Hold?",
"Selecting Multiple recipient for sending fax",
"Recording a Voice Name Over the Phone",
"Using the Virtual Calling Card",
"Recovering Deleted Messages",
"Choosing the Right RingCentral Online Service Plan",
"RingCentral Mobile Plan User Guide Download",
"Receiving Collect Calls",
"Payphone surcharges",
"Answering Rules Overview Video",
"RingCentral Secure Faxing",
"Transferring to an Extension After a Call is Placed on Hold",
"I added a new additional number to my account and was charged twice, how do I fix it?",
"Blocking Payphone Calls",
"Wrong Number Charges",
"Canceling a scheduled fax",
"Block incoming voice calls or faxes without Caller ID",
"Blocking Specific Phone Numbers or Areas from Dialing a RingCentral Account",
"Receiving The Mailbox is Full Message in a RingCentral Account",
"Allowing Only Specific Phone Numbers or Area Codes to Call a RingCentral Account",
"How do I avoid having to log into my online account to check messages all the time?",
"Fax Transmission Time",
"Receiving Faxes in .PDF Format",
"Using Personal Phone Numbers as Caller ID",
"Calling an International Location Using RingOut",
"RingOut Options: Turning Off the Current Location Prompt",
"Placing a call on Hold",
"Enabling RingOut",
"RingOut Options: Turning Off the Voice Prompt to Connect the Call",
"Forwarding to a Toll-Free Number or an Automated System",
"Using RingOut from an International Location",
"How to Start Logging in the Call Controller",
"RingCentral RingOut",
"Routing Calls and Playing Greetings Based on Hours of Operation",
"Software Not Required to Use our Service",
"Downloading the Call Controller with Softphone"
);